version: '3.8'
services:
  home:
    image: nginx:alpine
    container_name: home
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    networks:
      - home-network
networks:
  home-network:
    external: true
